### ISSUE TITLE
推荐

### ISSUE THREAD

**Issue by HiNLP** [Ddream-ai/nlhappy#1]
大佬好，毛遂自荐[bert4torch](https://github.com/Tongjilibo/bert4torch)这个仓库，是参考苏神的bert4keras的pytorch实现，目前已有500+star，欢迎试用和star

**Comment by Ddream-ai** [comment]
你好, 已经star, 这个nlhappy也是我马上要开源的一个快速开发nlp的库,目前也有参考bert4torch这个项目里面的代码,到时候也欢迎你star这个仓库

**Comment by HiNLP** [comment]
提前star
